### PR TITLE
bbtexures phase one

### PR DESCRIPTION
**Pull request by BBoldt**
I will do some more work on these, but I would like to hear your thoughts so far.

### CODE REVIEW

**Comment by gr8pefish** [comment]
Fantastic work so far, I love them! 

I could only briefly look at them (I have to go back to campus again soon), but I will give a more in-depth critique/analysis when I come home later tonight (if you want/don't mind). But for first glance I am very pleased :)

Note that I have added more backpacks in my most recent push (see [here](https://github.com/gr8pefish/IronBackpacks/blob/dev-1.8.9/changelog.txt#L7) for changelog details why), but they currently use the same icon and model textures [[example](https://github.com/gr8pefish/IronBackpacks/blob/dev-1.8.9/src/main/java/gr8pefish/ironbackpacks/registry/ItemRegistry.java#L119)] as the other backpacks of the same tier (iron/gold/diamond), so it won't show on the /textures directory, just so you know and if you want to add in new/different textures/models for those. You can add them as whatever name you want, I can deal with the technical details of file naming and whatnot, don't worry about that.

Once again though, whatever you choose to do is fine by me, and it is all appreciated :+1:

**Comment by BBoldt** [comment]
May need to move some stuff around and edit the jsons, I have no idea how they are supposed to work. I just threw in the textures and .json model files.

**Comment by BBoldt** [comment]
Heh I kinda forgot I made these

**Comment by BBoldt** [comment]
Did you get those models working?

**Comment by gr8pefish** [comment]
Not yet, I just pulled the PR in preparation for 1.9; I'd like to get a quick a dirty port out before I get swamped with finals. If I can't figure out the models right now I'll just use the old ones, but I figured I might as well try and figure it out in 1.9 rather than 1.8.

**Comment by BBoldt** [comment]
Yeah, just drop support for 1.8. Things are moving forward very quickly in 1.9.

**Comment by gr8pefish** [comment]
Yeah, that's the idea. I'll do a full fledged port/bug-fix spree once the summer rolls around, but for now i don't want to miss out on the first iterations of those 1.9 modpacks xD

**Pull request merged**
