### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by wlhlm**
This adds an initial German translation

---

BTW, I had some problems building the project. The gradle build script looks for an ominous "private" file, which makes the build fail. This fixed it for me:

``` diff
diff --git a/build.gradle b/build.gradle
index a5ad2d8..785df39 100644
--- a/build.gradle
+++ b/build.gradle
@@ -30,7 +30,7 @@ def gitHash = 'unknown'
 if (new File(projectDir, '.git').exists())
     gitHash = repo.log().find().abbreviatedId

-ext.priv = parseConfig(file('private'))
+ext.priv = parseConfig(file('gradle.properties'))

 repositories {}
```

### CODE REVIEW

**Comment by TehNut** [comment]
Which is why I told him to use my method from the 1.8 branch. But noooo... >.>

**Comment by gr8pefish** [comment]
Thanks, I appreciate the translation!

I just went with that method as it is simple enough to make a private file that contains the curseforge key, it is not like many people will have to deal with that. I will add a check to make sure it exists for the future though, so that it doesn't break for people like you.

**Comment by wlhlm** [comment]
Sounds good! Thanks for merging!

**Comment by gr8pefish** [comment]
Dank für deine Hilfe! ;)

**Pull request merged**
